import type { OnboardingProject } from "./types";

function section(title: string, content: string): string {
  return `## ${title}\n\n${content || "_Not yet generated._"}\n`;
}

export function assembleOnboardingPack(project: OnboardingProject): string {
  const { customer, outputs } = project;
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  const lines: string[] = [
    `# AI Onboarding Pack — ${customer.companyName}`,
    ``,
    `**Generated:** ${date}  `,
    `**Industry:** ${customer.industry.replace(/_/g, " ")}  `,
    `**Company size:** ${customer.companySize.replace(/_/g, " ")}  `,
    `**Use case:** ${customer.primaryUseCase || "TBD"}  `,
    `**Status:** ${project.status}  `,
    ``,
    `---`,
    ``,
    section("1. Executive Summary", outputs?.executiveSummary ?? ""),
    `---`,
    ``,
    section("2. Customer Discovery Summary", outputs?.customerDiscoverySummary ?? ""),
    `---`,
    ``,
    section("3. Current State Workflow", outputs?.currentStateWorkflow ?? ""),
    `---`,
    ``,
    section("4. Future State Workflow", outputs?.futureStateWorkflow ?? ""),
    `---`,
    ``,
    section("5. Requirements Matrix", outputs?.requirementsMatrix ?? ""),
    `---`,
    ``,
    section("6. Missing Information Log", outputs?.missingInformationLog ?? ""),
    `---`,
    ``,
    section("7. Integration and API Plan", outputs?.integrationAndApiPlan ?? ""),
    `---`,
    ``,
    section("8. Data Readiness Assessment", outputs?.dataReadinessAssessment ?? ""),
    `---`,
    ``,
    section("9. Implementation Plan", outputs?.implementationPlan ?? ""),
    `---`,
    ``,
    section("10. Risk Register Summary", outputs?.riskRegisterSummary ?? ""),
    `---`,
    ``,
    section("11. Pilot Success Plan", outputs?.pilotSuccessPlan ?? ""),
    `---`,
    ``,
    section("12. Stakeholder Communication Plan", outputs?.stakeholderCommunicationPlan ?? ""),
    `---`,
    ``,
    section("13. Engineering Handoff", outputs?.engineeringHandoff ?? ""),
    `---`,
    ``,
    section("14. Product Feedback Memo", outputs?.productFeedbackMemo ?? ""),
    `---`,
    ``,
    section("15. Next Actions Checklist", outputs?.nextActionsChecklist ?? ""),
    `---`,
    ``,
    `_Generated by the AI Onboarding Simulator — [ai-onboarding-simulator](https://github.com/georget-j/ai-onboarding-simulator)_`,
  ];

  return lines.join("\n");
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
